### ISSUE TITLE
Open-Closed principle violation

### ISSUE THREAD

**Issue by AlekseyKovalevsky** [mrblamber/finance-manager-bot#5]
https://github.com/mrblamber/finance-manager-bot/blob/3941574d846fd8085e78884db1a0d638c4aaa460/FinanceManager.Bot.Framework/Services/CommandService.cs#L16

ebat' govno. How to add a new command support? It requires a service rewriting.

**Comment by aliaksanderkazlou** [comment]
Izveni plz.

**Comment by tarnenok** [comment]
Ya ne videl koda huevee chem etot

**Comment by aliaksanderkazlou** [comment]
Izvinis
